rules:
  at-rule-name-case: lower
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-no-empty: true
  block-opening-brace-newline-after: always-multi-line
  block-opening-brace-newline-before: never-single-line
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always
  color-hex-case: lower
  color-no-invalid-hex: true
  comment-empty-line-before: always
  comment-no-empty: true
  comment-whitespace-inside: always
  declaration-block-no-duplicate-properties: true
  declaration-block-no-ignored-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always-multi-line
  declaration-block-trailing-semicolon: always
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-empty-line-before: never
  font-family-name-quotes: always-where-recommended
  function-comma-space-after: always
  function-name-case: lower
  function-parentheses-space-inside: never
  function-url-quotes: always
  function-whitespace-after: always
  indentation: 2
  length-zero-no-unit: true
  max-empty-lines: 2
  max-nesting-depth: 2
  media-feature-no-missing-punctuation: true
  no-duplicate-selectors: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: true
  number-leading-zero: always
  number-no-trailing-zeros: true
  property-case: lower
  property-no-vendor-prefix: true
  rule-nested-empty-line-before:
    - always
    - except:
      - first-nested
    - ignore:
      - after-comment
  rule-non-nested-empty-line-before:
    - always
    - ignore:
      - after-comment
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-quotes: never
  selector-class-pattern: ^(?:(?:a|o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9\\@]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  selector-max-compound-selectors: 3
  selector-max-empty-lines: 0
  selector-no-id: true
  selector-no-qualifying-type:
    - true
    - ignore:
      - attribute
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-case: lower
  selector-type-case: lower
  selector-type-no-unknown: true
  string-no-newline: true
  string-quotes: single
  unit-case: lower
  unit-no-unknown: true
  value-keyword-case: lower
  value-list-comma-space-after: always
  value-list-comma-space-before: never
