rules:
  indent: ["warn", 2]
  no-cond-assign: "warn"
  no-empty: ["warn", {allowEmptyCatch: true}]
  no-extra-semi: "warn"
  no-irregular-whitespace: "warn"
  no-unreachable: "warn"
  curly: "warn"
  no-eval: "warn"
  no-floating-decimal: "warn"
  no-global-assign: "warn"
  no-magic-numbers: ["warn", {ignore: [-1, 0, 1]}]
  no-octal: "warn"
  no-redeclare: "warn"
  no-unused-vars: "warn"
  block-spacing: "warn"
  brace-style: "warn"
  comma-style: ["warn", "last"]
  consistent-this: ["warn", "that"]
  eol-last: "warn"
  func-call-spacing: "warn"
  no-trailing-spaces: "warn"
  no-undef: "error"

env:
  node: true

parserOptions:
  sourceType: "module"
  ecmaVersion: 6
