<?php

namespace Chisel\WP;

use Chisel\Traits\HooksSingleton;
use Chisel\Helpers\ThemeHelpers;
use Chisel\Helpers\AjaxHelpers;
use Chisel\Helpers\AssetsHelpers;

/**
 * Class for enqueuing scripts and styles.
 *
 * @package Chisel
 */
final class Assets {

	use HooksSingleton;

	/**
	 * Front-end styles to be registered and enqueued.
	 *
	 * @var array
	 */
	private array $frontend_styles = array();

	/**
	 * Front-end styles to be registered and enqueued in footer.
	 *
	 * @var array
	 */
	private array $frontend_footer_styles = array();

	/**
	 * Front-end scripts to be registered and enqueued.
	 *
	 * @var array
	 */
	private array $frontend_scripts = array();

	/**
	 * Admin styles to be registered and enqueued.
	 *
	 * @var array
	 */
	private array $admin_styles = array();

	/**
	 * Admin scripts to be registered and enqueued.
	 *
	 * @var array
	 */
	private array $admin_scripts = array();

	/**
	 * Editor styles to be registered and enqueued.
	 *
	 * @var array
	 */
	private array $editor_styles = array();

	/**
	 * Editor scripts to be registered and enqueued.
	 *
	 * @var array
	 */
	private array $editor_scripts = array();

	/**
	 * Login page styles to be registered and enqueued.
	 *
	 * @var array
	 */
	private array $login_styles = array();

	/**
	 * Login page scripts to be registered and enqueued.
	 *
	 * @var array
	 */
	private array $login_scripts = array();

	/**
	 * WP React Refresh runtime dependency.
	 *
	 * @var string
	 */
	private string $refresh_runtime_dependency = 'wp-react-refresh-runtime';

	/**
	 * Set properties.
	 */
	public function set_properties(): void {
		// This is a required script for React Refresh. It is generated by Webpack and only exists in development mode.
		$runtime_script = array(
			'src'       => get_template_directory_uri() . '/build/runtime.js',
			'deps'      => array( $this->refresh_runtime_dependency ),
			'strategy'  => false,
			'condition' => array( ThemeHelpers::class, 'is_fast_refresh' ),
		);

		if ( ! is_admin() ) {
			$this->frontend_styles = array(
				'main' => array(),
			);

			$this->frontend_scripts = array(
				'runtime' => $runtime_script,
				'app'     => array(
					'deps'     => array( 'wp-i18n' ),
					'localize' => array(
						'name' => 'chiselScripts',
						'data' => array(
							'ajax' => array(
								'url'   => esc_url( AjaxHelpers::get_ajax_endpoint_url() ),
								'nonce' => wp_create_nonce( 'wp_rest' ), // this (wp_rest) authenticates users and allows using get_current_user functions in rest api endpoints.
							),
						),
					),
				),
			);

			if ( is_login() ) {
				$this->login_styles = array(
					'login' => array(),
				);

				$this->login_scripts = array(
					'runtime' => $runtime_script,
					'login'   => array(
						'localize' => array(
							'name' => 'chiselScripts',
							'data' => array(
								'logoData' => ThemeHelpers::get_login_page_logo_data(),
							),
						),
					),
				);
			}
		} else {
			$this->admin_styles = array(
				'admin' => array(),
			);

			$this->admin_scripts = array(
				'runtime' => $runtime_script,
				'admin'   => array(
					'localize' => array(
						'name' => 'chiselAdminScripts',
						'data' => array(
							'acfColorPickerPalette' => ThemeHelpers::get_colors_palette( 'acf' ),
						),
					),
				),
			);

			$this->editor_styles = array(
				'editor' => array(),
			);

			$this->editor_scripts = array(
				'editor' => array(
					'localize' => array(
						'name' => 'chiselEditorScripts',
						'data' => array(
							'icons' => array(
								'arrow-left'  => __( 'Arrow Left', 'chisel' ),
								'arrow-right' => __( 'Arrow Right', 'chisel' ),
								'minus'       => __( 'Minus', 'chisel' ),
								'plus'        => __( 'Plus', 'chisel' ),
							),
						),
					),
				),
			);
		}
	}

	/**
	 * Register action hooks.
	 */
	public function action_hooks(): void {
		add_action( 'init', array( $this, 'register_assets' ) );

		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_frontend_assets' ), 99 ); // Higher priority, overwrite plugins if needed.
		add_action( 'wp_footer', array( $this, 'enqueue_frontend_assets_in_footer' ), 11 ); // Higher priority, overwrite plugins if needed.
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_admin_assets' ), 11 );
		add_action( 'enqueue_block_editor_assets', array( $this, 'enqueue_editor_scripts' ) );
		add_action( 'login_enqueue_scripts', array( $this, 'enqueue_login_page_assets' ), 99 );

		// Removes PHP Notice: Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets).
		remove_action( 'admin_head', 'wp_check_widget_editor_deps' );
	}

	/**
	 * Register filter hooks.
	 */
	public function filter_hooks(): void {
		add_filter( 'script_loader_tag', array( $this, 'async_script' ), 99, 2 );
		add_filter( 'script_loader_tag', array( $this, 'defer_script' ), 99, 2 );
		add_filter( 'style_loader_tag', array( $this, 'preload_styles' ), 99, 2 );
	}

	/**
	 * Register assets.
	 */
	public function register_assets(): void {
		if ( ! is_admin() ) {
			$this->frontend_styles        = apply_filters( 'chisel_frontend_styles', $this->frontend_styles );
			$this->frontend_footer_styles = apply_filters( 'chisel_frontend_footer_styles', $this->frontend_footer_styles );
			$this->frontend_scripts       = apply_filters( 'chisel_frontend_scripts', $this->frontend_scripts );
			$this->login_styles           = apply_filters( 'chisel_login_styles', $this->login_styles );
			$this->login_scripts          = apply_filters( 'chisel_login_scripts', $this->login_scripts );

			if ( $this->frontend_styles ) {
				foreach ( $this->frontend_styles as $file_name => $args ) {
					$this->register_style( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
				}
			}

			if ( $this->frontend_footer_styles ) {
				foreach ( $this->frontend_footer_styles as $file_name => $args ) {
					$this->register_style( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
				}
			}

			if ( $this->frontend_scripts ) {
				foreach ( $this->frontend_scripts as $file_name => $args ) {
					$this->register_script( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
				}
			}

			if ( is_login() ) {
				if ( $this->login_styles ) {
					$login_styles_data = array();

					foreach ( $this->login_styles as $file_name => $args ) {
						$login_styles_data = $this->register_style( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
					}

					if ( isset( $login_styles_data['ver'] ) ) {
						wp_register_style( 'global-styles', false, array(), $login_styles_data['ver'] );
					}
				}

				if ( $this->login_scripts ) {
					foreach ( $this->login_scripts as $file_name => $args ) {
						$this->register_script( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
					}
				}
			}
		} else {
			$this->admin_styles   = apply_filters( 'chisel_admin_styles', $this->admin_styles );
			$this->admin_scripts  = apply_filters( 'chisel_admin_scripts', $this->admin_scripts );
			$this->editor_styles  = apply_filters( 'chisel_editor_styles', $this->editor_styles );
			$this->editor_scripts = apply_filters( 'chisel_editor_scripts', $this->editor_scripts );

			if ( $this->admin_styles ) {
				foreach ( $this->admin_styles as $file_name => $args ) {
					$this->register_style( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
				}
			}

			if ( $this->admin_scripts ) {
				foreach ( $this->admin_scripts as $file_name => $args ) {
					$this->register_script( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
				}
			}

			if ( $this->editor_styles ) {
				foreach ( $this->editor_styles as $file_name => $args ) {
					$this->register_style( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
				}
			}

			if ( $this->editor_scripts ) {
				foreach ( $this->editor_scripts as $file_name => $args ) {
					$this->register_script( AssetsHelpers::get_final_handle( $file_name ), $file_name, $args );
				}
			}
		}
	}

	/**
	 * Enqueue front-end assets.
	 */
	public function enqueue_frontend_assets(): void {
		$this->frontend_styles  = apply_filters( 'chisel_pre_enqueue_frontend_styles', $this->frontend_styles );
		$this->frontend_scripts = apply_filters( 'chisel_pre_enqueue_frontend_scripts', $this->frontend_scripts );

		if ( $this->frontend_styles ) {
			foreach ( $this->frontend_styles as $handle => $args ) {
				$enqueue_style = apply_filters( 'chisel_enqueue_frontend_style', true, $handle, $args );
				$style_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_style && wp_style_is( $style_handle, 'registered' ) ) {
					$this->enqueue_style( $style_handle, $args );

					// Enqueue js file for fast refresh of the css file.
					$this->enqueue_style_js_for_dev( $handle );
				}
			}
		}

		if ( $this->frontend_scripts ) {
			foreach ( $this->frontend_scripts as $handle => $args ) {
				$enqueue_script = apply_filters( 'chisel_enqueue_frontend_script', true, $handle, $args );
				$script_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_script && wp_script_is( $script_handle, 'registered' ) ) {
					$this->enqueue_script( $script_handle, $args );
				}
			}
		}
	}

	/**
	 * Enqueue front-end styles in footer, ie. Gravity Forms custom styles.
	 */
	public function enqueue_frontend_assets_in_footer(): void {
		$this->frontend_footer_styles = apply_filters( 'chisel_pre_enqueue_frontend_footer_styles', $this->frontend_footer_styles );

		if ( $this->frontend_footer_styles ) {
			foreach ( $this->frontend_footer_styles as $handle => $args ) {
				$enqueue_style = apply_filters( 'chisel_enqueue_frontend_footer_style', true, $handle, $args );
				$style_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_style && wp_style_is( $style_handle, 'registered' ) ) {
					$this->enqueue_style( $style_handle, $args );

					// Enqueue js file for fast refresh of the css file.
					$this->enqueue_style_js_for_dev( $handle );
				}
			}
		}
	}

	/**
	 * Enqueue admin assets.
	 */
	public function enqueue_admin_assets(): void {
		$this->admin_styles  = apply_filters( 'chisel_pre_enqueue_admin_styles', $this->admin_styles );
		$this->admin_scripts = apply_filters( 'chisel_pre_enqueue_admin_scripts', $this->admin_scripts );

		if ( $this->admin_styles ) {
			foreach ( $this->admin_styles as $handle => $args ) {
				$enqueue_style = apply_filters( 'chisel_enqueue_admin_style', true, $handle, $args );
				$style_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_style && wp_style_is( $style_handle, 'registered' ) ) {
					$this->enqueue_style( $style_handle, $args );

					// Enqueue js file for fast refresh of the css file.
					$this->enqueue_style_js_for_dev( $handle );
				}
			}
		}

		if ( $this->admin_scripts ) {
			foreach ( $this->admin_scripts as $handle => $args ) {
				$enqueue_script = apply_filters( 'chisel_enqueue_admin_script', true, $handle, $args );
				$script_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_script && wp_script_is( $script_handle, 'registered' ) ) {
					$this->enqueue_script( $script_handle, $args );
				}
			}
		}
	}

	/**
	 * Enqueue editor scripts.
	 */
	public function enqueue_editor_scripts(): void {
		$this->editor_styles  = apply_filters( 'chisel_pre_enqueue_editor_styles', $this->editor_styles );
		$this->editor_scripts = apply_filters( 'chisel_pre_enqueue_editor_scripts', $this->editor_scripts );

		if ( $this->editor_styles ) {
			foreach ( $this->editor_styles as $handle => $args ) {
				$enqueue_style = apply_filters( 'chisel_enqueue_editor_style', true, $handle, $args );
				$style_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_style && wp_style_is( $style_handle, 'registered' ) ) {
					$this->enqueue_style( $style_handle, $args );

					// Enqueue js file for fast refresh of the css file.
					$this->enqueue_style_js_for_dev( $handle );
				}
			}
		}

		if ( $this->editor_scripts ) {
			foreach ( $this->editor_scripts as $handle => $args ) {
				$enqueue_script = apply_filters( 'chisel_enqueue_editor_script', true, $handle, $args );
				$script_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_script && wp_script_is( $script_handle, 'registered' ) ) {
					$this->enqueue_script( $script_handle, $args );
				}
			}
		}
	}

	/**
	 * Enqueue login page scripts.
	 */
	public function enqueue_login_page_assets(): void {
		$stylesheet = wp_get_global_stylesheet();

		if ( empty( $stylesheet ) ) {
			return;
		}

		$this->login_styles  = apply_filters( 'chisel_pre_enqueue_login_styles', $this->login_styles );
		$this->login_scripts = apply_filters( 'chisel_pre_enqueue_login_scripts', $this->login_scripts );

		wp_add_inline_style( 'global-styles', $stylesheet );
		wp_enqueue_style( 'global-styles' );

		if ( $this->login_styles ) {
			foreach ( $this->login_styles as $handle => $args ) {
				$enqueue_style = apply_filters( 'chisel_enqueue_login_style', true, $handle, $args );
				$style_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_style && wp_style_is( $style_handle, 'registered' ) ) {
					$this->enqueue_style( $style_handle, $args );

					// Enqueue js file for fast refresh of the css file.
					$this->enqueue_style_js_for_dev( $handle );
				}
			}
		}

		if ( $this->login_scripts ) {
			foreach ( $this->login_scripts as $handle => $args ) {
				$enqueue_script = apply_filters( 'chisel_enqueue_login_script', true, $handle, $args );
				$script_handle  = AssetsHelpers::get_final_handle( $handle );

				if ( $enqueue_script && wp_script_is( $script_handle, 'registered' ) ) {
					$this->enqueue_script( $script_handle, $args );
				}
			}
		}
	}

	/**
	 * Async scripts by handle.
	 *
	 * @param string $tag
	 * @param string $handle
	 *
	 * @return string
	 */
	public function async_script( string $tag, string $handle ): string {
		if ( is_admin() ) {
			return $tag;
		}

		$scripts = array();

		if ( $scripts ) {
			foreach ( $scripts as $script_handle ) {
				if ( $handle === $script_handle ) {
					$tag = str_replace( ' src', ' async src', $tag );
				}
			}
		}

		return $tag;
	}

	/**
	 * Defer scripts by handle.
	 *
	 * @param string $tag
	 * @param string $handle
	 *
	 * @return string
	 */
	public function defer_script( string $tag, string $handle ): string {
		if ( is_admin() || is_login() ) {
			return $tag;
		}

		$scripts = array();

		if ( $scripts ) {
			foreach ( $scripts as $script_handle ) {
				if ( $handle === $script_handle ) {
					$tag = str_replace( ' src', ' defer src', $tag );
				}
			}
		}

		return $tag;
	}

	/**
	 * Preload styles by handle.
	 *
	 * @param string $tag
	 * @param string $handle
	 *
	 * @return string
	 */
	public function preload_styles( string $tag, string $handle ): string {
		if ( is_admin() ) {
			return $tag;
		}

		$styles_handles = array(
			'wp-block-library',
		);

		$styles_handles_start_with = array(
			'gform_',
			'block',
		);

		if ( $styles_handles ) {
			foreach ( $styles_handles as $style_handle ) {
				if ( $handle === $style_handle ) {
					$tag = $this->preload_style( $tag );
				}
			}
		}

		if ( $styles_handles_start_with ) {
			foreach ( $styles_handles_start_with as $style_handle ) {
				if ( strpos( $handle, $style_handle ) === 0 ) {
					$tag = $this->preload_style( $tag );
				}
			}
		}

		return $tag;
	}

	/**
	 * Preload style tag.
	 *
	 * @param string $tag
	 *
	 * @return string
	 */
	private function preload_style( string $tag ): string {
		$preload_tag = str_replace( "rel='stylesheet'", "rel='preload' as='style'", $tag );
		$tag         = $preload_tag . str_replace( "media='all'", "media='print' onload='this.media=\"all\"'", $tag );

		return $tag;
	}

	/**
	 * Register style wrapper function.
	 *
	 * @param string $handle
	 * @param string $file_name
	 * @param array  $args
	 *
	 * @return ?array
	 */
	private function register_style( string $handle, string $file_name, array $args ): ?array {
		$asset_data = $this->get_asset( $file_name, 'css' );

		$src       = isset( $args['src'] ) ? $args['src'] : $this->get_style_src( $file_name );
		$deps      = isset( $args['deps'] ) ? $args['deps'] : array();
		$ver       = isset( $args['ver'] ) ? $args['ver'] : $asset_data['version'];
		$media     = isset( $args['media'] ) ? $args['media'] : 'all';
		$condition = isset( $args['condition'] ) ? $args['condition'] : null;

		// Use condition to determine if the style should be registered. It can be either a boolean or a function.
		if ( $condition !== null ) {
			if ( is_callable( $condition ) ) {
				$condition = call_user_func( $condition );
			}

			if ( ! $condition ) {
				return null;
			}
		}

		if ( $asset_data['dependencies'] ) {
			$deps = wp_parse_args( $asset_data['dependencies'], $deps );
		}

		wp_register_style( $handle, $src, $deps, $ver, $media );

		// Register js file for fast refresh of the css file.
		if ( ThemeHelpers::is_fast_refresh() ) {
			$this->register_script(
				'style-' . $handle,
				$file_name,
				array(
					'src' => $this->get_style_src( $file_name, true ),
				),
			);
		}

		return array(
			'src'       => $src,
			'deps'      => $deps,
			'ver'       => $ver,
			'media'     => $media,
			'condition' => $condition,
			'handle'    => $handle,
		);
	}

	/**
	 * Enqueue script wrapper function.
	 *
	 * @param string $handle - full script handle.
	 * @param array  $args
	 *
	 * @return array
	 */
	private function enqueue_style( string $handle, array $args ): array {
		$inline = isset( $args['inline'] ) ? $args['inline'] : '';

		if ( $inline ) {
			wp_add_inline_style( $handle, $inline['data'] );
		}

		wp_enqueue_style( $handle );

		return array(
			'handle' => $handle,
		);
	}

	/**
	 * Register script wrapper function.
	 *
	 * @param string $handle
	 * @param string $file_name
	 * @param array  $args
	 *
	 * @return ?array
	 */
	private function register_script( string $handle, string $file_name, array $args ): ?array {
		$asset_data = $this->get_asset( $file_name, 'js' );

		$src       = isset( $args['src'] ) ? $args['src'] : $this->get_script_src( $file_name );
		$deps      = isset( $args['deps'] ) ? $args['deps'] : array();
		$ver       = isset( $args['ver'] ) ? $args['ver'] : $asset_data['version'];
		$strategy  = isset( $args['strategy'] ) ? $args['strategy'] : array(
			'in_footer' => true,
			'strategy'  => 'defer',
		); // Strategy can be a boolean, which determines if the script should be enqueued in the footer, or an array with the following keys: 'in_footer':boolean and 'strategy':string (defer or async).
		$condition = isset( $args['condition'] ) ? $args['condition'] : null;

		// Use condition to determine if the script should be registered. It can be either a boolean or a function.
		if ( $condition !== null ) {
			if ( is_callable( $condition ) ) {
				$condition = call_user_func( $condition );
			}

			if ( ! $condition ) {
				return null;
			}
		}

		if ( $asset_data['dependencies'] ) {
			$deps = wp_parse_args( $asset_data['dependencies'], $deps );
		}

		wp_register_script( $handle, $src, $deps, $ver, $strategy );

		return array(
			'src'       => $src,
			'deps'      => $deps,
			'ver'       => $ver,
			'strategy'  => $strategy,
			'condition' => $condition,
			'handle'    => $handle,
		);
	}

	/**
	 * Enqueue script wrapper function.
	 *
	 * @param string $handle - full script handle.
	 * @param array  $args
	 *
	 * @return array
	 */
	private function enqueue_script( string $handle, array $args ): array {
		$localize = isset( $args['localize'] ) ? $args['localize'] : array();
		$inline   = isset( $args['inline'] ) ? $args['inline'] : '';

		if ( $localize ) {
			wp_localize_script( $handle, $localize['name'], $localize['data'] );
		}

		if ( $inline ) {
			wp_add_inline_script( $handle, $inline['data'], $inline['position'] );
		}

		wp_enqueue_script( $handle );
		$this->set_script_translations( $handle, $args );

		return array(
			'localize' => $localize,
			'handle'   => $handle,
		);
	}

	/**
	 * Wrapper for wp_set_script_translations function.
	 *
	 * @param string $handle
	 * @param array  $args
	 *
	 * @return void
	 */
	private function set_script_translations( string $handle, array $args ): void {
		if ( isset( $args['deps'] ) && in_array( 'wp-i18n', $args['deps'], true ) ) {
			wp_set_script_translations( AssetsHelpers::get_final_handle( $handle ), 'chisel', get_template_directory() . '/languages' );
		}
	}

	/**
	 * Enqueue style for development (fast refresh) mode.
	 *
	 * @param string $handle
	 *
	 * @return void
	 */
	private function enqueue_style_js_for_dev( string $handle ): void {
		if ( ThemeHelpers::is_fast_refresh() ) {
			wp_enqueue_script( 'style-' . AssetsHelpers::get_final_handle( $handle ) );
		}
	}

	/**
	 * Get the script src url.
	 *
	 * @param string $file_name
	 *
	 * @return string
	 */
	private function get_script_src( string $file_name ): string {
		return get_template_directory_uri() . '/build/scripts/' . $file_name . '.js';
	}

	/**
	 * Get the style src url.
	 *
	 * @param string $file_name
	 * @param bool   $refresh_script
	 *
	 * @return string
	 */
	private function get_style_src( string $file_name, bool $refresh_script = false ): string {
		if ( $refresh_script ) {
			return get_template_directory_uri() . '/build/styles/' . $file_name . '.js';
		}

		return get_template_directory_uri() . '/build/styles/' . $file_name . '.css';
	}

	/**
	 * Get the asset data.
	 *
	 * @param string $file_name
	 * @param string $type
	 *
	 * @return array
	 */
	private function get_asset( string $file_name, string $type ): array {
		if ( $type === 'css' ) {
			$asset_path = get_template_directory() . '/build/styles/' . $file_name . '.asset.php';
		} else {
			$asset_path = get_template_directory() . '/build/scripts/' . $file_name . '.asset.php';
		}

		$asset = array(
			'dependencies' => array(),
			'version'      => ThemeHelpers::get_theme_version(),
		);

		if ( is_file( $asset_path ) ) {
			$asset = include $asset_path;

			// We must remove that dependency for styles in fast refresh mode. For some reason styles are not loaded otherwise.
			if (
				$type === 'css' &&
				ThemeHelpers::is_fast_refresh() &&
				( $index = array_search( $this->refresh_runtime_dependency, $asset['dependencies'] ) ) !== false // phpcs:ignore
			) {
				unset( $asset['dependencies'][ $index ] );
			}
		}

		return $asset;
	}
}
