name: Test

on: [push]

jobs:
  Test:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [12]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - uses: ankane/setup-mysql@v1
        with:
          mysql-version: 8.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn

      - name: Setup PHP with fail-fast
        uses: shivammathur/setup-php@v2
        with:
          # https://stackoverflow.com/q/69910916
          php-version: '7.4'
          extensions: mysqli, curl, exif, fileinfo, mbstring, openssl, gd

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prepare Links
        run: yarn prepare-links

      - name: Prepare WP CLI
        run: yarn workspace chisel-plugin-wordpress run prepare

      - run: php -v

      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: yarn test
