name: Test

on: [push]

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [12]
        # os: [ubuntu-20.04, windows-2019, macos-11]
        # node-version: [12, 14] # https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: ankane/setup-mysql@v1
        with:
          mysql-version: 8.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn

      - name: Setup PHP with fail-fast
        uses: shivammathur/setup-php@v2
        with:
          # https://stackoverflow.com/q/69910916
          php-version: '7.4'
          extensions: mysqli, curl, exif, fileinfo, mbstring, openssl, gd

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prepare links
        run: yarn prepare-links

      - name: Prepare WP CLI
        run: yarn workspace chisel-plugin-wordpress run prepare

      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: yarn test

      - name: Save coverage as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS, NODE_VERSION
        env:
          OS: ${{ matrix.os }}
          NODE_VERSION: ${{ matrix.node-version }}
