name: Test

on: [push]

jobs:
  Test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn

      - name: Enable colors
        run: export FORCE_COLOR=3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test wp
