name: Test

on: [push]

jobs:
  Test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prepare Links
        run: yarn prepare-links

      - name: Prepare WP CLI
        run: yarn workspace chisel-plugin-wordpress run prepare

      - run: php -v

      - name: Run tests
        env:
          FORCE_COLOR: 3
        run: yarn test generator/wp

      - run: ls -lah
        if: failure()

      - run: ls -lah ./.jest-projects
        if: failure()

      - run: ls -lah ./.jest-projects/**/wp
        if: failure()

      - run: cat ./.jest-projects/**/wp/wp-config.php
        if: failure()

      - run: cat ./.jest-projects/**/wp/wp-config-local.php
        if: failure()

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: wp-config
          path: '**/wp-config.php'
